version: '3.8'

services:
  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - CI=true
    command: bun run test
    ports:
      - "5174:5174" # Test UI port if needed
    networks:
      - test-network

  frontend-test-watch:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
    command: bun run test:watch
    ports:
      - "5174:5174"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge 