services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - SERVER_PORT=${SERVER_PORT:-8000}
      - SERVER_HOST=${SERVER_HOST:-0.0.0.0}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - INPUT_FILE=${INPUT_FILE:-data/input.txt}
    # Remove the command override since it's now in Dockerfile.dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000} 